#!/usr/bin/env bash
# Bash Script By Phoenix
# Scripts accepts ip address and pings the Ip

if [ $# -lt 1 ] || [ $# -gt 1 ]
then
	echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}";
else
	ping -c5 "$1"
fi
