#!/usr/bin/env bash
# Bash script By Phoenix

num=1
while [ "$num" -le 10 ]
do
	if [ "$num" -eq 4 ]
	then
		echo "bad luck"
	elif [ "$num" = 8 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	((num++))
done
