#!/usr/bin/env bash
# Bash Script by Phoenix

num=1
while [ "$num" -le 20 ]
do
	echo "$num"
	if [ "$num" = 4 ]
	then
		echo "bad luck from China"
	elif [ "$num" = 9 ]
	then
		echo "bad luck from Japan"
	elif [ "$num" = 17 ]
	then
		echo "bad luck from Italy"
	fi
	((num++))
done
