#!/bin/bash

SERVICE_NAME="gunicorn.service"

# Check if the service is active
if sudo systemctl is-active --quiet $SERVICE_NAME; then
    echo "Reloading $SERVICE_NAME gracefully..."

    # Get the PID of the master Gunicorn process
    # MASTER_PID=$(pgrep gunicorn | head -1
    MASTER_PID=$(sudo systemctl show -p MainPID --value $SERVICE_NAME)

    # Reload the Gunicorn service using hot reload
    sudo kill -s HUP $MASTER_PID

    # Check if the reload was successful
    if sudo systemctl is-active --quiet $SERVICE_NAME; then
        echo "$SERVICE_NAME reloaded gracefully"
    else
        echo "Failed to reload $SERVICE_NAME"
    fi
else
    echo "$SERVICE_NAME is not active. Starting it..."
    sudo systemctl start $SERVICE_NAME

    # Check if the start was successful
    if sudo systemctl is-active --quiet $SERVICE_NAME; then
        echo "$SERVICE_NAME started successfully"
    else
        echo "Failed to start $SERVICE_NAME"
    fi
fi
